/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.barbeiroDorminhoco;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author jonathalima
 */
public class FrmBarbeiroDorminhoco extends javax.swing.JFrame {
    Barbeiro b1 = new Barbeiro();
    Thread t1 = new Thread(b1);
            
    Cliente c1 = new Cliente();
    Thread t2 = new Thread(c1); 
    
    public FrmBarbeiroDorminhoco() {
        initComponents();
    }

    Thread changeColor = new Thread(){
        public void run() {
            while(true) {
                
                if(Barbeiro.cortando)
                    cadeiraBarbeiro.setBackground(Color.RED);
                else if(Barbeiro.dormindo)
                    cadeiraBarbeiro.setBackground(Color.BLUE);
                else
                    cadeiraBarbeiro.setBackground(Color.GREEN);
                
                switch(Barbeiro.waiting) {
                    case 1 :
                        //cadeiraBarbeiro.setBackground(Color.RED);
                        cadeiraEspera1.setBackground(Color.RED);
                        cadeiraEspera2.setBackground(Color.GREEN);
                        cadeiraEspera3.setBackground(Color.GREEN);
                        cadeiraEspera4.setBackground(Color.GREEN);
                        cadeiraEspera5.setBackground(Color.GREEN);
                        break;
                    case 2:
                        //cadeiraBarbeiro.setBackground(Color.RED);
                        cadeiraEspera1.setBackground(Color.RED);
                        cadeiraEspera2.setBackground(Color.RED);
                        cadeiraEspera3.setBackground(Color.GREEN);
                        cadeiraEspera4.setBackground(Color.GREEN);
                        cadeiraEspera5.setBackground(Color.GREEN);
                        break;
                    case 3:
                        //cadeiraBarbeiro.setBackground(Color.RED);
                        cadeiraEspera1.setBackground(Color.RED);
                        cadeiraEspera2.setBackground(Color.RED);
                        cadeiraEspera3.setBackground(Color.RED);
                        cadeiraEspera4.setBackground(Color.GREEN);
                        cadeiraEspera5.setBackground(Color.GREEN);
                        break;
                    case 4 :
                        //cadeiraBarbeiro.setBackground(Color.RED);
                        cadeiraEspera1.setBackground(Color.RED);
                        cadeiraEspera2.setBackground(Color.RED);
                        cadeiraEspera3.setBackground(Color.RED);
                        cadeiraEspera4.setBackground(Color.RED);
                        cadeiraEspera5.setBackground(Color.GREEN);
                        break;
                    case 5 :
                        //cadeiraBarbeiro.setBackground(Color.RED);
                        cadeiraEspera1.setBackground(Color.RED);
                        cadeiraEspera2.setBackground(Color.RED);
                        cadeiraEspera3.setBackground(Color.RED);
                        cadeiraEspera4.setBackground(Color.RED);
                        cadeiraEspera5.setBackground(Color.RED);
                        break;
                    default :
                        //cadeiraBarbeiro.setBackground(Color.BLUE);
                        cadeiraEspera1.setBackground(Color.GREEN);
                        cadeiraEspera2.setBackground(Color.GREEN);
                        cadeiraEspera3.setBackground(Color.GREEN);
                        cadeiraEspera4.setBackground(Color.GREEN);
                        cadeiraEspera5.setBackground(Color.GREEN);
                        break;
                }
            }
        }
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadeiraEspera2 = new javax.swing.JButton();
        lblCadeiraBarbeiro = new javax.swing.JLabel();
        cadeiraEspera3 = new javax.swing.JButton();
        cadeiraEspera5 = new javax.swing.JButton();
        cadeiraEspera1 = new javax.swing.JButton();
        cadeiraEspera4 = new javax.swing.JButton();
        cadeiraEspera = new javax.swing.JLabel();
        lblPorta = new javax.swing.JLabel();
        cadeiraBarbeiro = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cadeiraEspera2.setBackground(Color.GREEN);
        cadeiraEspera2.setFocusable(false);

        lblCadeiraBarbeiro.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblCadeiraBarbeiro.setText("Cadeira Barbeiro");

        cadeiraEspera3.setBackground(Color.GREEN);
        cadeiraEspera3.setFocusable(false);

        cadeiraEspera5.setBackground(Color.GREEN);
        cadeiraEspera5.setFocusable(false);

        cadeiraEspera1.setBackground(Color.GREEN);
        cadeiraEspera1.setFocusable(false);

        cadeiraEspera4.setBackground(Color.GREEN);
        cadeiraEspera4.setFocusable(false);

        cadeiraEspera.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cadeiraEspera.setText("Cadeiras de espera");

        cadeiraBarbeiro.setBackground(java.awt.Color.blue);
        cadeiraBarbeiro.setFocusable(false);

        btnAbrir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAbrir.setText("Abrir Barbearia");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 250));
        jLabel2.setText("BARBEIRO DORMINDO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("CADEIRAS DISPONÍVEIS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("CADEIRAS OCUPADAS");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Fechar Barbearia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblCadeiraBarbeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(cadeiraEspera)
                .addGap(171, 171, 171))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAbrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(cadeiraBarbeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadeiraEspera1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cadeiraEspera2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cadeiraEspera3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(cadeiraEspera4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadeiraEspera5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadeiraEspera)
                            .addComponent(lblCadeiraBarbeiro))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cadeiraEspera1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadeiraEspera2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadeiraEspera3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadeiraEspera5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadeiraEspera4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cadeiraBarbeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        //cadeiraBarbeiro.setOpaque(true);
        //cadeiraBarbeiro.setOpaque(true);
        //cadeiraBarbeiro.setOpaque(true);
        //cadeiraBarbeiro.setOpaque(true);
        //cadeiraBarbeiro.setOpaque(true);
        //cadeiraBarbeiro.setOpaque(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        t1.start();
        t2.start();
        changeColor.start();
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        t2.stop();
        JOptionPane.showMessageDialog(null, "Barbearia fechada, ninguém mais pode entrar!");
    }//GEN-LAST:event_jButton1ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBarbeiroDorminhoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBarbeiroDorminhoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBarbeiroDorminhoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBarbeiroDorminhoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            FrmBarbeiroDorminhoco frame = new FrmBarbeiroDorminhoco();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton cadeiraBarbeiro;
    private javax.swing.JLabel cadeiraEspera;
    private static javax.swing.JButton cadeiraEspera1;
    private static javax.swing.JButton cadeiraEspera2;
    private static javax.swing.JButton cadeiraEspera3;
    private static javax.swing.JButton cadeiraEspera4;
    private static javax.swing.JButton cadeiraEspera5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCadeiraBarbeiro;
    private javax.swing.JLabel lblPorta;
    // End of variables declaration//GEN-END:variables
}
